DROP TABLE IF EXISTS `faturas`;

CREATE TABLE IF NOT EXISTS `faturas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` ENUM('PAGA','A PAGAR') NOT NULL DEFAULT 'A PAGAR' ,
  `cartao_id` INT(10) UNSIGNED NOT NULL,
  `baixa_em` DATE NULL DEFAULT NULL,
  `vencimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
CHECKSUM = 1;