DROP TABLE IF EXISTS `transacoes`;

CREATE TABLE IF NOT EXISTS `transacoes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(18,2) UNSIGNED NOT NULL ,
  `status` ENUM('PAGO','A PAGAR') NOT NULL DEFAULT 'A PAGAR' ,
  `entidade_id` INT(10) UNSIGNED NOT NULL,
  `categoria_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fatura_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `baixa_em` DATETIME NULL DEFAULT NULL,
  `vencimento` DATETIME NULL DEFAULT NULL,
  `inserido_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
CHECKSUM = 1;